events { 
    worker_connections 1024; 
}

http{
    upstream bakend_servers{
        server backend: 8080;
    }

    server {
        listen 8080;
        location / {
            proxy_pass http://bakend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

        add_header X-Backend-Server $upstream_addr;
    }
}
}