input{
    beats{
        port => 5044
    }
}
filter{
    if [container][name] == "nginx-lb"{
        grok {
            match => { "message" => "%{IPORHOST:remote_addr} - %{DATA:remote_user} \[%{HTTPDATE:time_local}\] \"%{WORD:request_method} %{DATA:request_path} HTTP/%{NUMBER:http_version}\" %{NUMBER:status} %{NUMBER:body_bytes_sent} \"%{DATA:http_referer}\" \"%{DATA:http_user_agent}\" \"%{DATA:http_x_forwarded_for}\"" }
        }

        date{
            match => [ "time_local", "dd/MMM/yyyy:HH:mm:ss Z" ]
            target => "@timestamp"
        }

        mutate{
            convert => {
                "status" => "integer"
                "body_bytes_sent" => "integer"
            }
        }

        geoip{
            source => "remote_addr"
            target => "geoip"
        }

        useragent{
            source => "http_user_agent"
            target => "useragent"
        }
    }
}

output{
    elasticsearch{
        hosts => ["http://elasticsearch:9200"]
        index => "nginx-access-%{+YYYY.MM.dd}"
    }
    stdout{
        codec => rubydebug
    }
}