spring.application.name=backend
spring.profiles.active=local

# Use localhost if you set up Port Forwarding in VirtualBox
# Use the VM IP if you are on a Bridged/Host-only adapter
spring.datasource.url=jdbc:mysql://localhost:3306/cfr_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true