spring.application.name=backend

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.datasource.url=jdbc:mysql://10.152.4.59:3306/cfr_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root_password
spring.jpa.hibernate.ddl-auto=update

spring.session.store-type=jdbc